
spring:
  rabbitmq:
    host: 192.168.226.132
    port: 5672
    username: admin
    password: admin
  application:
    name: item-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka1:2002/eureka

---
spring:
  profiles: item1

server:
  port: 8003
---
spring:
  profiles: item2

server:
  port: 8002

#shishi

